# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-lRMaxMdFLHsA-5gKEVZqfAvahk50bwp
"""

class CompteBancaire :
  def _init_(self,nom_proprietaire,solde=0.0):
    self.nom_proprietair=nom_proprietaire
    self.solde=float(solde)
  def deposer(self,montant):
      self.solde=self.solde+montant
  def retirer(self,montant):
     if montant < self.solde:
        self.solde=self.solde-montant
     else :
       print("Erreur")
  def afficher_solde(self):
     print(self.nom_proprietair)
     print(self.solde)

from os.path import normcase
from abc import ABC, abstractmethod
class Personne(ABC):
      def _init_(self,nom, prenom, age):
          nom=self.nom
          prenom=self.prenom
          age=self.age
      def afficher_infos(self):
          print(self.nom)
          print(self.prenom)
          print(self.age)
class Etudiant(Personne)
      def _init_(self,matricule,notes)
           matricule=self.matricule
           notes=list(self.notes)
      def  jouter_note(self,note):
           self.notes.append(note)
      def moyenne(self):
          moyenne=sum(self.notes)\len(self.notes)
      def afficher_infos(self):
          print(self.notes)
          print(self.moyenne)
class Enseignant(Personne)
     def _init_(self,specialite,salaire)
          self.specialite=specialite
          self.salaire=salaire
     def afficher_infos()
          print()
class Ecole()
     def _init_(self,nom,liste_etudiants,liste_enseignants)
         self.nom=nom
         self.liste_etudiants=liste_etudiants
         self.liste_enseignants=liste_enseignants