# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1ZotKbfHtSciaCFjWFMNopCX-vuiTuY
"""

nom=input("Quel votre nom ")
salaire= int(input("quel votre salaire horaire"))
heures=int(input("combien d'heures"))
def horaire_sup():
    if heures > 40 :
       heuresSupplémentaire=heures-40
       salaireTotale=salaire*40+heuresSupplémentaire*salaire*1.5
       return(nom,"votre salire totale est",salaireTotale)
    else :
       salaireTotale=salaire*40
       return(nom,"votre salire totale est",salaireTotale)
horaire_sup()

def calculation(x,y):
    somme=x+y
    différence=x-y
    return somme,différence
calculation(1,5)

n=int(input("saisir un nombre entier"))
def factorielle(n):
    i=1
    nfactoriell=1
    while i<=n :
      nfactoriell*=i
      i+=1
    return nfactoriell
print(factorielle(n))

m=int(input("saisir un nombre entier"))
def multiplication(m):
    for i in range(1,11):
      print(m*i)
multiplication(m)

import math
L=int(input("saisir un nombre entier"))
def carréparfait():
    if L%math.sqrt(L)==0 :
       print("carréparfait")
    else :
       print("Noncarréparfait")
carréparfait()

chaine=input("saisir un caractère")
def carac():
    for caractère in chaine :
      print(caractère)
carac()

phrase=