# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zcRiNKNaIk_j01YiCuoKuMDWrgE44vYU
"""

First_dict = { "Appareil": "Laptop", "Marque": "IBM", "Carte mère": "MSI Z490", "Carte Graphique":"GeForce RTX 3070", "RAM": "16G", "Processeur": "Intel core i7-G11", "SSD": "1 To" }
First_dict["RAM"]="32G"
print(First_dict)
Clés=[]
Valeurs=[]
for clé,val in First_dict.items() :
    Clés.append(clé)
    Valeurs.append(val)

print(Clés)
print(Valeurs)
paires=list(First_dict.items())
print(paires)



First_dict['Processeur'],First_dict['Carte Graphique']=First_dict['Carte Graphique'],First_dict['Processeur']
print(First_dict)
First_dict["Système d’exploitation"]="Windows 10"
print(First_dict)

notes_eleves = { "Amine": 15.5, "Yassine": 19.0, "Reda": 14.2, "Malak": 8.7, "Manal": 20.0, "Ahmed": 7.5,"Saad": 11.3, "Hannae": 9.8 }
etudiantAdmis={}
etudiantNonAdmis={}
for clé,val in notes_eleves.items():
  if val>=10 :
    etudiantAdmis[clé]= val
  else:
    etudiantNonAdmis[clé]= val
print(etudiantAdmis)
print(etudiantNonAdmis)

etudiantAdmis={'Amine': 15.5, 'Yassine': 19.0, 'Reda': 14.2, 'Manal': 20.0, 'Saad': 11.3}
etudiantNonAdmis={'Malak': 8.7, 'Ahmed': 7.5, 'Hannae': 9.8}
First_dict = { "Appareil": "Laptop", "Marque": "IBM", "Carte mère": "MSI Z490", "Carte Graphique":"GeForce RTX 3070" }
etudiantAdmis.update(etudiantNonAdmis)
etudiantAdmis.update(First_dict)
dictionnairefinal=etudiantAdmis
print(dictionnairefinal)

Clé=['Appareil', 'Marque', 'Carte mère', 'Carte Graphique', 'RAM', 'Processeur', 'SSD']
Valeur=['Laptop', 'IBM', 'MSI Z490', 'GeForce RTX 3070', '32G', 'Intel core i7-G11', '1 To']
print(dict(zip(Clé,Valeur)))

etudiantAdmis={'Amine': 15.5, 'Yassine': 19.0, 'Reda': 14.2, 'Manal': 20.0, 'Saad': 11.3}

dictionnaire=sorted(etudiantAdmis.items(),key=lambda x: x[1])
print(dictionnaire)

etudiant_info = (("Prénom","Yasmine"), ("Âge",22), ("Filière","Informatique"), ("Moyenne générale",17.4))
print(etudiant_info [2])
print(etudiant_info [:2])
etudiant_info = (("Prénom","Yasmine"), ("Âge",22), ("Filière","Informatique"), ("Moyenne générale",17.4))
tuple1=(("la mention","Très Bien"),("Année",2024))
tuplefinal=tuple1+etudiant_info
print(tuplefinal)

