# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Y5BRn1ODT6tKwGKJTva-6lN8nnz3wC9
"""

nom=input("Quel votre nom ")
age=int(input("quel votre age "))
print("bonjour",nom,"votre age et",age)



nom=input("Quel votre nom ")
salaire= int(input("quel votre salaire horaire"))
heures=int(input("combien d'heures"))
if heures > 40 :
  heuresSupplémentaire=heures-40
  salaireTotale=salaire*40+heuresSupplémentaire*salaire*1.5
  print(nom,"votre salire totale est",salaireTotale)
else :
  salaireTotale=salaire*40
  print(nom,"votre salire totale est",salaireTotale)

try:
  nom=input("Quel votre nom ")
  salaire= int(input("quel votre salaire horaire"))
  heures=int(input("combien d'heures"))
  if heures > 40 :
     heuresSupplémentaire=heures-40
     salaireTotale=salaire*40+heuresSupplémentaire*salaire*1.5
     print(nom,"votre salire totale est",salaireTotale)
  else :
     salaireTotale=salaire*40
     print(nom,"votre salire totale est",salaireTotale)
except ValueError :
     print("entre non numérique")

n1= int(input("entre n1"))
n2= int(input("entre n2"))
x=n1*n2
if x>0 :
  print("le produit est positif")
elif x>0 :
  print("le produit est negatif")
else :
  print("le produit est null")

N= int(input("entre N "))
i=1
S=0
while i<=N :
  S=i+S
  i+=1
  print(S)

chaineOriginal="DevIA"
chaineInversée=""
i=len(chaineOriginal)

while i>0:
  chaineInversée=chaineInversée+chaineOriginal[i-1]
  i-=1
  print(chaineInversée)

import math
y1=int(input("entre Y1"))
y2=int(input("entre y1"))
x1=int(input("entre X1"))
x2=int(input("entre x1"))
Distance= math.sqrt((x2-x1**2)-(y2-y1**2))
print(Distance)